// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrECdyVY7glwEqBjZLDX1giv9DSIEJUM0',
    appId: '1:780050316538:web:8747880d4f5ebac38ddd43',
    messagingSenderId: '780050316538',
    projectId: 'finalproject-35cb3',
    authDomain: 'finalproject-35cb3.firebaseapp.com',
    storageBucket: 'finalproject-35cb3.firebasestorage.app',
    measurementId: 'G-R90FCNCQQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCutw0rzk-ThOC-3t-_HnZQYpTTGtvgUkY',
    appId: '1:780050316538:android:bb473bc764070d678ddd43',
    messagingSenderId: '780050316538',
    projectId: 'finalproject-35cb3',
    storageBucket: 'finalproject-35cb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOKiHIHbr2HE5RWGg0bTR1yCFrw99FoH8',
    appId: '1:780050316538:ios:4dc21bec8aa6c2718ddd43',
    messagingSenderId: '780050316538',
    projectId: 'finalproject-35cb3',
    storageBucket: 'finalproject-35cb3.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOKiHIHbr2HE5RWGg0bTR1yCFrw99FoH8',
    appId: '1:780050316538:ios:4dc21bec8aa6c2718ddd43',
    messagingSenderId: '780050316538',
    projectId: 'finalproject-35cb3',
    storageBucket: 'finalproject-35cb3.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrECdyVY7glwEqBjZLDX1giv9DSIEJUM0',
    appId: '1:780050316538:web:1988fac69145e9758ddd43',
    messagingSenderId: '780050316538',
    projectId: 'finalproject-35cb3',
    authDomain: 'finalproject-35cb3.firebaseapp.com',
    storageBucket: 'finalproject-35cb3.firebasestorage.app',
    measurementId: 'G-22R9JSH4GJ',
  );
}
